### ISSUE TITLE
Debian Packaging

### ISSUE THREAD

**Issue by t-8ch** [archlinux/libudev0-shim#1]
Are you interested in carrying Debian packaging in the source tree? (I will implement  it)

It would consist of a directory `debian/` with ~10 files.
This is probably overkill but maybe you want to have it.

**Comment by falconindy** [comment]
No thanks. Packaging should be kept within the district, not littered around upstream projects. Notice we keep the Arch Linux packaging elsewhere...

**Comment by smcv** [comment]
This was packaged in Debian a while ago (and indirectly, in Ubuntu universe): https://tracker.debian.org/pkg/libudev0-shim
