### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by eworm-de** [archlinux/libudev0-shim#12]
This has some nice additions and important changes now. Will we see a release any time soon?

**Comment by evelikov** [comment]
Yup will do in a second. Thanks o/

Fwiw going forward the idea is to move the repo to the Arch gitlab instance, so you should have access as well.

**Comment by evelikov** [comment]
Pushed a signed v2 tag. I've used my usual GPG key (8703B6700E7EE06D7A39B8D6EDAE37B02CEB490D), which was to sign releases for mesa, libdrm and a few less known projects.

Will switch to "proper" releases, as we jump the gitlab train.

**Comment by eworm-de** [comment]
Thanks a lot! Already pushed to your testing repositories:

https://gitlab.archlinux.org/archlinux/packaging/packages/libudev0-shim/-/commit/fd1b6c099435e47c2bbafe26bca5b8ce19d1d060
https://gitlab.archlinux.org/archlinux/packaging/packages/lib32-libudev0-shim/-/commit/d1ade7820b685ab1542525fa833c49cbbae1c714
